platform :ios, '8.0'
target 'YGSchool' do
pod 'AFNetworking', '~> 3.0.0-beta.2'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJRefresh', '~> 3.0.7'
pod 'MJExtension', '~> 3.0.9'
pod 'IQKeyboardManager', '~> 3.3.4'
pod 'Masonry', '~> 0.6.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'XMLDictionary', '~> 1.4'
pod 'MJExtension', '~> 3.0.9'
pod 'ReactiveCocoa','2.5'
pod 'MWPhotoBrowser'
pod 'AMap3DMap'
pod 'FSCalendar'
pod 'AMapLocation'

end
